/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fbf8fc",
        "surface-dim": "#dbd9dc",
        "surface-bright": "#fbf8fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f6",
        "surface-container": "#efedf0",
        "surface-container-high": "#e9e7eb",
        "surface-container-highest": "#e4e2e5",
        "on-surface": "#1b1b1e",
        "on-surface-variant": "#44474e",
        "inverse-surface": "#303033",
        "inverse-on-surface": "#f2f0f3",
        outline: "#75777f",
        "outline-variant": "#c5c6cf",
        "surface-tint": "#4e5e81",
        primary: "#000516",
        "on-primary": "#ffffff",
        "primary-container": "#0b1e3d",
        "on-primary-container": "#7686ab",
        "inverse-primary": "#b6c6ee",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#b6c6ee",
        "on-primary-fixed": "#071b3a",
        "on-primary-fixed-variant": "#364768",
        secondary: "#755b00",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed255",
        "on-secondary-container": "#735a00",
        "secondary-fixed": "#ffe08e",
        "secondary-fixed-dim": "#ecc246",
        "on-secondary-fixed": "#241a00",
        "on-secondary-fixed-variant": "#584400",
        tertiary: "#150100",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#440500",
        "on-tertiary-container": "#e15b42",
        "tertiary-fixed": "#ffdad3",
        "tertiary-fixed-dim": "#ffb4a5",
        "on-tertiary-fixed": "#3f0400",
        "on-tertiary-fixed-variant": "#8a1c09",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#fbf8fc",
        "on-background": "#1b1b1e",
        "surface-variant": "#e4e2e5",
        success: "#2E7D32",
        "on-success": "#ffffff",
        // ── Admin Panel Design Tokens ─────────────────────────────────────
        "admin-navy":       "#0B1E3D",
        "admin-navy-dark":  "#060F1F",
        "admin-navy-mid":   "#152742",
        "admin-navy-light": "#1E3A5F",
        "admin-gold":       "#C9A227",
        "admin-gold-light": "#E4BB4F",
        "admin-gold-pale":  "#F5E4A8",
        "admin-coral":      "#C1442D",
        "admin-coral-light":"#E06A55",
        "admin-seafoam":    "#F4F7F6",
        "admin-seafoam-mid":"#E8EEEC",
        "admin-surface":    "#FFFFFF",
        "admin-text":       "#0B1E3D",
        "admin-text-sub":   "#4A5568",
        "admin-border":     "#D1DAE3",
        "admin-success":    "#1B7A45",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700", letterSpacing: "-0.02em" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600", letterSpacing: "0.01em" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500", letterSpacing: "0.05em" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "1.75rem",
        "card": "28px",
        full: "9999px",
      },
      spacing: {
        "base": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
      },
      boxShadow: {
        "card": "0 4px 20px rgba(0, 5, 22, 0.15)",
        "card-hover": "0 8px 32px rgba(0, 5, 22, 0.22)",
        "stat": "0 8px 32px rgba(0, 5, 22, 0.3)",
        "nav": "0 2px 24px rgba(0, 5, 22, 0.12)",
      },
      maxWidth: {
        "container": "1280px",
      },
      backgroundImage: {
        "navy-gradient": "linear-gradient(135deg, #000516 0%, #0b1e3d 50%, #1a3060 100%)",
        "gold-gradient": "linear-gradient(135deg, #fed255 0%, #ecc246 100%)",
        "hero-gradient": "linear-gradient(180deg, rgba(0,5,22,0.7) 0%, rgba(0,5,22,0.3) 50%, rgba(0,5,22,0.8) 100%)",
      },
      animation: {
        "pulse-badge": "pulse-badge 2s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
        "shimmer": "shimmer 1.5s infinite",
      },
      keyframes: {
        "pulse-badge": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.05)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
    },
  },
  plugins: [],
}
